"""add autogenerate ivite code

Revision ID: 44b51fa25778
Revises: 69b0a7495791
Create Date: 2025-08-15 13:37:06.115452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44b51fa25778"
down_revision: Union[str, None] = "69b0a7495791"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_users_phone"), "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_phone"), "users", type_="unique")
    # ### end Alembic commands ###
